# Generated by Django 4.1.2 on 2022-10-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('FICCAO CIENTIFICA', 'Ficção Científica'), ('COMEDIA', 'Comédia'), ('TERROR', 'Terror'), ('OUTROS', 'Outros')], max_length=20),
        ),
    ]
