# Generated by Django 4.1.2 on 2022-11-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_alter_filme_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('FICCAO CIENTIFICA', 'Ficção Científica'), ('COMEDIA', 'Comédia'), ('TERROR', 'Terror'), ('COMEDIA DRAMATICA', 'Comédia Dramática'), ('ACAO', 'Ação')], max_length=20),
        ),
    ]
